version: "3"

services:
  rest-api:
    build: .
    ports:
      - 1337:1337
    volumes:
      - ./config:/opt/app/config
  database:
    restart: always
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=apipassword
      - POSTGRES_DB=toothpick
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: local
