version: "3"

services:
  rest-api:
    container_name: toothpick_api
    build: .
    ports:
      - 1338:1338
    volumes:
      - ./config:/opt/app/config
  database:
    container_name: toothpick_db
    build: ./database
    restart: always
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=apipassword
      - POSTGRES_DB=toothpick
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: local
